name: EMP SCRAPER - AfrobeatInstrumental_01
on:
  push:
    paths:
      - '.github/workflows/emp-afrobeat_instrumental_01.yml'
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    concurrency:
      group: emp-group
    timeout-minutes: 6600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Setup Ollama
        uses: pydantic/ollama-action@v3
        with:
          model: ${{ secrets.OLLAMA_MODEL }}

      - name: Set up Dependencies
        run : |
          sudo apt update -y
          sudo apt install ffmpeg libmp3lame0 -y
          sudo apt install curl -y && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          node -v
          nvm install 22
          node -v
          git config --global --add safe.directory /app
          sudo apt install unzip chromium-browser -y

      - name: Download & Unzip Scraper
        run : |
          sudo curl --ssl-no-revoke --cookie "" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" -L -o tonics-scrape.zip "${{ secrets.TONICS_SCRAPE_ARCHIVE }}"
          unzip -P ${{ secrets.TONICS_SCRAPE_ARCHIVE_PASSWORD }} "tonics-scrape.zip" && rm "tonics-scrape.zip"

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Run Scraper
        working-directory: ./tonics-scrape
        run : |
          npm install
          rm -r Exported/*
          until node --expose-gc --no-warnings index.js -o AfrobeatInstrumental_01 -i -b -c 2; do
              if [ $? -eq 255 ]; then
                  echo "Process exited with code 255. Restarting..."
                  sleep 2
              else
                  echo "Process exited with code $?. Not restarting."
                  break
              fi
          done

        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          ROTATING_PROXY_USERNAME: ${{ secrets.ROTATING_PROXY_USERNAME }}
          ROTATING_PROXY_PASSWORD: ${{ secrets.ROTATING_PROXY_PASSWORD }}
          ROTATING_PROXY_PORT: ${{ secrets.ROTATING_PROXY_PORT }}
          ROTATING_PROXY_SERVER: ${{ secrets.ROTATING_PROXY_SERVER }}
          ROTATING_PROXY_TO_ROTATE: ${{ secrets.ROTATING_PROXY_TO_ROTATE }}
          TONICS_FILEMANAGER: ${{ secrets.EMP_TONICS_FILEMANAGER }}
          TONICS_EMAIL: ${{ secrets.EMP_TONICS_EMAIL }}
          TONICS_PASSWORD: ${{ secrets.EMP_TONICS_PASSWORD }}
          TONICS_FOLDER: ${{ secrets.EMP_TONICS_FOLDER }}
          TONICS_DATABASE_HOST: ${{ secrets.TONICS_DATABASE_HOST }}
          TONICS_DATABASE_PORT: ${{ secrets.TONICS_DATABASE_PORT }}
          TONICS_DATABASE_NAME: ${{ secrets.TONICS_DATABASE_NAME }}
          TONICS_DATABASE_USERNAME: ${{ secrets.TONICS_DATABASE_USERNAME }}
          TONICS_DATABASE_PASSWORD: ${{ secrets.TONICS_DATABASE_PASSWORD }}
          OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}
          OLLAMA_MODEL: ${{ secrets.OLLAMA_MODEL }}
          OPEN_ROUTER: ${{ secrets.OPEN_ROUTER }}
          OPEN_ROUTER_MODEL: ${{ secrets.OPEN_ROUTER_MODEL }}

      - name: Update Rclone config
        uses: AnimMouse/setup-rclone/update-config@v1
        with:
          rclone_config_secret_name: RCLONE_CONFIG
          token: ${{ secrets.GH_PAT }}